import React, { useState, useEffect } from 'react';
import Footer from '../../components/Footer';
import './News.css';

const STATIC_NEWS = [
  { id:1, title:"OpenAI launches GPT-4o with real-time voice and vision", category:"OpenAI", time:"2 hours ago", emoji:"🤖", desc:"The latest GPT-4o model brings real-time voice conversations and live camera vision to ChatGPT free users globally.", url:"https://openai.com/blog", hot:true },
  { id:2, title:"Google Gemini 2.0 Flash now available to all users for free", category:"Google", time:"5 hours ago", emoji:"✨", desc:"Google releases Gemini 2.0 Flash — the fastest and most capable free AI model yet, with 1M token context window.", url:"https://blog.google", hot:true },
  { id:3, title:"ElevenLabs launches new Indian English voice collection", category:"Audio AI", time:"1 day ago", emoji:"🎙️", desc:"ElevenLabs adds 20 new Indian English voices with regional accents — perfect for Hindi content creators.", url:"https://elevenlabs.io/blog", hot:false },
  { id:4, title:"Midjourney V7 releases with cinematic quality upgrade", category:"Image AI", time:"1 day ago", emoji:"🖼️", desc:"Midjourney V7 significantly improves photorealism, text accuracy in images, and prompt following capabilities.", url:"https://midjourney.com", hot:true },
  { id:5, title:"Suno AI hits 10 million songs generated in 30 days", category:"Music AI", time:"2 days ago", emoji:"🎵", desc:"Suno AI celebrates a major milestone as 10 million songs are generated by creators worldwide using their platform.", url:"https://suno.com/blog", hot:false },
  { id:6, title:"Cursor AI raises $100M — now valued at $2.5 billion", category:"Coding AI", time:"2 days ago", emoji:"💻", desc:"The AI code editor Cursor secures massive funding round as developer AI tools see unprecedented adoption growth.", url:"https://cursor.sh", hot:false },
  { id:7, title:"CapCut adds real-time AI translation for 50 languages", category:"Video AI", time:"3 days ago", emoji:"🎬", desc:"CapCut's new AI Translation feature automatically dubs videos into 50 languages with synced lip movements.", url:"https://capcut.com", hot:false },
  { id:8, title:"Perplexity AI launches Pages — create web articles from search", category:"Research AI", time:"3 days ago", emoji:"🔍", desc:"Perplexity introduces Pages, allowing users to transform search results into beautifully formatted web articles.", url:"https://perplexity.ai", hot:false },
  { id:9, title:"Adobe Firefly 3 integrates into Photoshop with generative expand", category:"Design AI", time:"4 days ago", emoji:"🎨", desc:"Adobe brings Firefly 3 to Photoshop with improved generative fill, expand, and new vector generation capabilities.", url:"https://adobe.com/firefly", hot:false },
  { id:10, title:"HeyGen launches real-time AI avatar video calls", category:"Avatar AI", time:"5 days ago", emoji:"👤", desc:"HeyGen introduces real-time AI avatar mode for video calls — your avatar attends meetings while you stay off-camera.", url:"https://heygen.com", hot:false },
  { id:11, title:"Notion AI now reads your entire workspace to answer questions", category:"Productivity", time:"5 days ago", emoji:"⚡", desc:"Notion Q&A feature now indexes your entire workspace so AI can answer questions across all your pages and databases.", url:"https://notion.so", hot:false },
  { id:12, title:"Runway ML Gen-3 Alpha produces Hollywood-quality video clips", category:"Video AI", time:"6 days ago", emoji:"🎥", desc:"Runway's latest Gen-3 Alpha model creates cinematic video clips with accurate motion, lighting, and character consistency.", url:"https://runwayml.com", hot:false },
];

const CATEGORIES = ['All', 'OpenAI', 'Google', 'Image AI', 'Video AI', 'Audio AI', 'Coding AI', 'Design AI', 'Research AI', 'Avatar AI', 'Productivity', 'Music AI'];

export default function News() {
  const [filter, setFilter] = useState('All');
  const [search, setSearch] = useState('');
  const [saved, setSaved] = useState(() => {
    try { return JSON.parse(localStorage.getItem('saved_news') || '[]'); } catch { return []; }
  });

  const toggleSave = (id) => {
    setSaved(prev => {
      const next = prev.includes(id) ? prev.filter(n => n !== id) : [...prev, id];
      localStorage.setItem('saved_news', JSON.stringify(next));
      return next;
    });
  };

  const filtered = STATIC_NEWS.filter(n => {
    const matchCat = filter === 'All' || n.category === filter;
    const matchSearch = !search || n.title.toLowerCase().includes(search.toLowerCase()) || n.desc.toLowerCase().includes(search.toLowerCase());
    return matchCat && matchSearch;
  });

  const hot = STATIC_NEWS.filter(n => n.hot);

  return (
    <div className="news-page">
      <div className="orb orb1"/><div className="orb orb2"/>
      <div className="news-container">

        {/* Hero */}
        <div className="news-hero">
          <h1 className="news-title">📰 AI News & Updates</h1>
          <p className="news-sub">Latest launches, updates, and breakthroughs from the world of AI. Updated daily.</p>
          <div className="news-search-wrap">
            <span>🔍</span>
            <input className="news-search" type="text" placeholder="Search AI news…" value={search} onChange={e => setSearch(e.target.value)}/>
          </div>
        </div>

        {/* Hot this week */}
        <div className="news-section">
          <h2 className="news-section-title">🔥 Hot This Week</h2>
          <div className="news-hot-grid">
            {hot.map(n => (
              <a key={n.id} className="news-hot-card" href={n.url} target="_blank" rel="noopener noreferrer">
                <div className="news-hot-emoji">{n.emoji}</div>
                <div className="news-hot-info">
                  <span className="news-hot-badge">{n.category}</span>
                  <h3>{n.title}</h3>
                  <span className="news-time">{n.time}</span>
                </div>
              </a>
            ))}
          </div>
        </div>

        {/* Category filter */}
        <div className="news-filter-row">
          {CATEGORIES.map(c => (
            <button key={c} className={`news-filter-btn${filter===c?' active':''}`} onClick={() => setFilter(c)}>{c}</button>
          ))}
        </div>

        {/* All news */}
        <div className="news-section">
          <h2 className="news-section-title">📋 All News {filter!=='All'&&`— ${filter}`}</h2>
          <div className="news-list">
            {filtered.map(n => (
              <div key={n.id} className="news-item">
                <div className="news-item-emoji">{n.emoji}</div>
                <div className="news-item-content">
                  <div className="news-item-meta">
                    <span className="news-cat-badge">{n.category}</span>
                    {n.hot && <span className="news-hot-tag">🔥 Hot</span>}
                    <span className="news-time">{n.time}</span>
                  </div>
                  <h3 className="news-item-title">{n.title}</h3>
                  <p className="news-item-desc">{n.desc}</p>
                  <div className="news-item-actions">
                    <a href={n.url} target="_blank" rel="noopener noreferrer" className="news-read-btn">Read More →</a>
                    <button className={`news-save-btn${saved.includes(n.id)?' saved':''}`} onClick={() => toggleSave(n.id)}>
                      {saved.includes(n.id) ? '🔖 Saved' : '📌 Save'}
                    </button>
                    <button className="news-share-btn" onClick={() => {
                      if (navigator.share) navigator.share({ title: n.title, url: n.url });
                      else { navigator.clipboard.writeText(n.url); alert('Link copied!'); }
                    }}>📤 Share</button>
                  </div>
                </div>
              </div>
            ))}
            {filtered.length === 0 && (
              <div className="news-empty">
                <div style={{fontSize:48,marginBottom:12}}>🔍</div>
                <h3>No news found</h3>
                <p>Try a different search or category</p>
              </div>
            )}
          </div>
        </div>

        {/* Newsletter */}
        <div className="news-newsletter">
          <div className="newsletter-inner">
            <div className="newsletter-emoji">📧</div>
            <h3>Get AI News in Your Inbox</h3>
            <p>Weekly digest of the most important AI tool updates, launches, and tips — delivered every Monday.</p>
            <div className="newsletter-form">
              <input type="email" placeholder="your@email.com" className="newsletter-input"/>
              <button className="newsletter-btn">Subscribe Free →</button>
            </div>
          </div>
        </div>

      </div>
      <Footer />
    </div>
  );
}
